// constants used for Security Attributes etc.
// NSLog(@"kSecAttrService: %@", kSecAttrService);
export enum kSec {

    kSecReturnAttributes = "r_Attributes",
    kSecReturnData = "r_Data",
    kSecReturnRef = "r_Ref",
    kSecMatchLimit = "m_Limit",
    kSecMatchLimitAll = "m_LimitAll",
    kSecClass = "class",
    kSecClassKey = "keys",
    kSecClassIdentity = "idnt",
    kSecClassCertificate = "cert",
    kSecClassGenericPassword = "genp",
    kSecClassInternetPassword = "inet",
    kSecAttrService = "svce",
    kSecAttrAccount = "acct",
    kSecAttrAccessGroup = "agrp",
    kSecAttrLabel = "labl",
    kSecAttrCreationDate = "cdat",
    kSecAttrAccessControl = "accc",
    kSecAttrGeneric = "gena",
    kSecAttrSynchronizable = "sync",
    kSecAttrModificationDate = "mdat",
    kSecAttrServer = "srvr",
    kSecAttrDescription = "desc",
    kSecAttrComment = "icmt",
    kSecAttrCreator = "crtr",
    kSecAttrType = "type",
    kSecAttrScriptCode = "scrp",
    kSecAttrAlias = "alis",
    kSecAttrIsInvisible = "invi",
    kSecAttrIsNegative = "nega",
    kSecAttrHasCustomIcon = "cusi",
    kSecProtectedDataItemAttr = "prot",
    kSecAttrAccessible = "pdmn",
    kSecAttrAccessibleWhenUnlocked = "ak",
    kSecAttrAccessibleAfterFirstUnlock = "ck",
    kSecAttrAccessibleAlways = "dk",
    kSecAttrAccessibleWhenUnlockedThisDeviceOnly = "aku",
    kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly = "akpu",
    kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly = "cku",
    kSecAttrAccessibleAlwaysThisDeviceOnly = "dku",
    kSecValueData = "v_Data",
}
